## Python Programming Language -> MCA 2nd Semester Syllabus

## NumPy Library

In [2]:
# Introduction to NumPy x 
# Creation of One-Dimensional Arrays x
# Multi-Dimensional Arrays x
# Array Manipulation Operations x
# Arithematic operations x
# Aggregate Operations x
# Reshaping of an Array x
# Array Indexing x
# Array Slicing x
# Iterating NumPy Arrays x
# Element-wise Operations
# Insert Row/Columns
# Append Row/Columns

## What is NumPy

In [3]:
# NumPy is a general-purpose array-processing package. 
# NumPy is a Python library used for working with arrays.
# It provides a high-performance multidimensional array object and tools for working with these arrays. 
# It is the fundamental package for scientific computing with Python. 
# It also has wide variety of mathematical functions for working in domain of linear algebra, fourier transform, and matrices.
# NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.
# NumPy stands for Numerical Python. It is an open-source software.

## Why Use NumPy

In [4]:
# In Python we have lists that serve the purpose of arrays, but they are slow to process.
# NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
# The array object in NumPy is called ndarray
# It provides a lot of supporting functions that make working with ndarray very easy.
# Arrays are very frequently used in data science, where speed and resources are very important.
# Data Science: is a branch of CS where we study how to store, use and analyze data for deriving information from it.

## Which Language is NumPy written in

In [5]:
# NumPy is a Python library and is written partially in Python.
# But most of the parts that require fast computation are written in C or C++.

## Why is NumPy Faster Than Lists

In [6]:
# NumPy is faster than Python lists primarily due to its implementation in C
# Which allows for more efficient memory management and optimized operations. 
# NumPy arrays are stored at one continuous place in memory unlike lists.
# So processes can access and manipulate them very efficiently.

# Here are some reasons why NumPy outperforms lists:

# Homogeneous Data Types: 
# NumPy arrays have elements of the same data type.
# Which allows for more efficient memory storage and faster computation compared to Python lists.
# Python list can contain elements of different types.

# Vectorized Operations:
# NumPy supports vectorized operations, which means that operations are applied to all elements of an array simultaneously.
# Leveraging the highly optimized C and Fortran code behind NumPy's functions. 
# This avoids the need for explicit looping over elements, as required with Python lists.

# Contiguous Memory Allocation:
# NumPy arrays are stored in contiguous memory blocks, which allows for efficient memory access and faster computations.
# Especially for large datasets. 
# Python lists, on the other hand, store references to objects scattered across memory, leading to slower access times.

# Optimized Algorithms:
# NumPy provides a wide range of optimized algorithms for common mathematical operations.
# Such as linear algebra, Fourier transforms, and random number generation. 
# These algorithms are implemented in C and Fortran, making them significantly faster than Python lists.

# Parallelism: 
# It is optimized to work with latest CPU architectures.
# NumPy can take advantage of parallel processing capabilities of modern CPUs.
# Through libraries like Intel MKL (Math Kernel Library) or OpenBLAS, further enhancing its performance for certain operations.

## Difference between Numpy array and Python list

In [ ]:
# Data type storage
# Importing module
# Numerical opertions
# Modification capabilities
# Consumes less memory
# Faster as compared to python lists
# Convinient to use

## Installation of numpy library  

In [1]:
!pip install numpy

In [2]:
import numpy as np

## Numpy array vs list

In [4]:
# numpy array
numbers = np.array([1,2,3,4,5])
print(type(numbers))
print(numbers)

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [3]:
# list
numbers = [1,2,3,4,5]
print(type(numbers))
print(numbers)

<class 'list'>
[1, 2, 3, 4, 5]


## How to Create NumPy Array

In [11]:
# numpy array
x = [1,2,3,4,5]
numbers = np.array(x) # passing list as an argument after creating it seperately
print(type(numbers))
print(numbers)

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [8]:
# numpy array
numbers = np.array([1,2,3,4,5]) # passing list as an argument directly
print(type(numbers))
print(numbers)

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [16]:
# taking user input and storing it into numpy array
num = []
for i in range(1,6):
    n = int(input(f"Enter number at position {i} : "))
    num.append(n)

numbers = np.array(num)
print(type(numbers))
print(numbers)

Enter number at position 1 : 1
Enter number at position 2 : 2
Enter number at position 3 : 3
Enter number at position 4 : 4
Enter number at position 5 : 5
<class 'numpy.ndarray'>
[1 2 3 4 5]


## Types of numpy array

In [12]:
# 1d Array creation and checking
x = [1,2,3,4,5]
numbers = np.array(x)
print(type(numbers))
print(f"This is a {numbers.ndim}D array")
print(numbers)

<class 'numpy.ndarray'>
This is a 1D array
[1 2 3 4 5]


In [11]:
# 2d Array creation and checking
# x = [[1,2,3,4,5]]
x = [[1,2,3,4,5],[6,7,8,9,10]]
numbers = np.array(x)
print(type(numbers))
print(f"This is a {numbers.ndim}D array")
print(numbers)

<class 'numpy.ndarray'>
This is a 2D array
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [10]:
# 3d Array creation and checking
# x = [[[1,2,3,4,5]]]
x = [[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]]
numbers = np.array(x)
print(type(numbers))
print(f"This is a {numbers.ndim}D array")
print(numbers)

<class 'numpy.ndarray'>
This is a 3D array
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]


In [9]:
# nd Array creation and checking
x = [1,2,3,4,5]
numbers = np.array(x, ndmin = 10)
print(type(numbers)) 
print(f"This is a {numbers.ndim}D array")
print(numbers)

<class 'numpy.ndarray'>
This is a 10D array
[[[[[[[[[[1 2 3 4 5]]]]]]]]]]


## Special types of numpy arrays

In [41]:
# Arrays filled with 0's
array_1d_zero = np.zeros(5)
print(array_1d_zero)
print()
array_2d_zero = np.zeros((3,3))
print(array_2d_zero)

[0. 0. 0. 0. 0.]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [42]:
# Arrays filled with 1's
array_1d_one = np.ones(5)
print(array_1d_one)
print()
array_2d_one = np.ones((3,3))
print(array_2d_one)

[1. 1. 1. 1. 1.]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [44]:
# Empty array stores the values of previously created array thats why it is filled with 1
numbers = np.empty(5)
print(numbers)

[1. 1. 1. 1. 1.]


In [47]:
# Array with a given range of elements
arr1 = np.arange(5)
print(arr1)

arr2 = np.arange(1,5)
print(arr2)

[0 1 2 3 4]
[1 2 3 4]


In [50]:
# Array diagnal element filled with 1's | identity matrix
numbers = np.eye(5)
print(numbers)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


## How to Create NumPy Arrays with Random Numbers

In [52]:
# rand() functions is used to generate a random value between 0 and 1
numbers = np.random.rand(5)
print(numbers)

[0.18237896 0.56063737 0.38818051 0.64332655 0.42259576]


In [53]:
# randn() functions is used to generate a random value close to 0. This may return positive as well as negative number as well
numbers = np.random.randn(5)
print(numbers)

[-0.4822003   1.37091378  0.60688528 -1.01841444  1.11122839]


In [72]:
# randint() functions is used to generate a random value between a given range
# systax -  np.random.randint(min, max, total_values)
numbers = np.random.randint(1,5)
print(numbers)

4


In [77]:
numbers = np.random.randint(1,10,5)
print(numbers)

[5 5 9 6 9]


## What is Data Type of NumPy Array

In [ ]:
# 1 bool_ = Boolean (True or False) stored as a byte
# 2 int = Default integer type (same as C long; normally either int64 or int32)
# 3 Intc = Identical to C int (normally int32 or int64)
# 4 Intp = Integer used for indexing (same as C ssize_t; normall either int32 or int64)
# 5 int8 = Byte (-128 to 127)
# 6 int16 = Integer (-32768 to 32767)
# 7 int32 = Integer (-2147483648 to 2147483647)
# 8 int64 = Integer (-9223372036854775808 to 9223372036854775807)
# 9 uint8 = Unsigned integer (0 to 255)
# 10 uint16 = Unsigned integer (0 to 65535)
# 11 uint32 = Unsigned integer (0 to 4294967295)
# 12 uint64 = Unsigned integer (0 to 18446744073709551615)
# 13 float = Shorthand for float64
# 14 float16 = Half precision float: sign bit, 5 bits exponent, 10 bits mantissa
# 15 float32 = Single precision float: sign bit, 8 bits exponent mantissats
# 16 float64 = Double precision float: sign bit, 11 bits mantissa
# 17 complex_ = Shorthand for complex128
# 18 complex64 = Complex number, represented by two 32-bit floats (real and imaginary components)
# 19 complex128 = Complex number, represented by two 64-bit floats (real and imaginary components)

In [ ]:
# i - integer
# b - boolean
# u - unsigned integer
# f - float
# C - complex float
# m - timedelta
# M - datetime
# 0 - object
# S - string
# U - Unicode string
# V - the fixed chunk of memory for other types (void)

In [17]:
# Array of integer data type
var = np.array([1,2,3,4,5])
print(f"Data type is : {var.dtype}")
print(var)

Data type is : int32
[1 2 3 4 5]


In [18]:
# Array of float data type
var = np.array([1.0,2.0,3.0,4.0,5.0])
print(f"Data type is : {var.dtype}")
print(var)

Data type is : float64
[1. 2. 3. 4. 5.]


In [19]:
# Array of character or string data type
var = np.array(["A","B","C","D","E"])
print(f"Data type is : {var.dtype}")
print(var)

Data type is : <U1
['A' 'B' 'C' 'D' 'E']


In [20]:
# Array of mixed data type
var = np.array([1,2,3,4,5,"A","B","C","D","E"])
print(f"Data type is : {var.dtype}")
print(var)

Data type is : <U11
['1' '2' '3' '4' '5' 'A' 'B' 'C' 'D' 'E']


In [14]:
# Array type conversion int32 to int8
var = np.array([1,2,3,4,5])
print(f"Data type is : {var.dtype}")
print(var)
print()
var = np.array([1,2,3,4,5], dtype = np.int8) 
print(f"Data type is : {var.dtype}")
print(var)

Data type is : int32
[1 2 3 4 5]

Data type is : int8
[1 2 3 4 5]


In [16]:
# Array type conversion int to float
x = np.array([1,2,3,4,5], dtype = "f")
print(f"Data type is : {x.dtype}")
print(x)

Data type is : float32
[1. 2. 3. 4. 5.]


In [23]:
# Array type conversion using type conversion function
x = np.array([1,2,3,4,5])
var = np.float32(x)
print(f"Data type is : {x.dtype}")
print(x)

print(f"Data type is : {var.dtype}")
print(var)

Data type is : int32
[1 2 3 4 5]
Data type is : float32
[1. 2. 3. 4. 5.]


## NumPy - Array Manipulation

## NumPy Arithmetic Operations

In [ ]:
# we can use symbols like +-*/ or inbuilt functions like add,subtract etc
# a+b = np.add(a,b)
# a-b = np.subtract(a,b)
# a*b = np.multiply(a,b)
# a/b = np.divide(a,b)
# a%b = np.mod(a,b)
# a**b = np.power(a,b)
# 1/a = np.reciprocal(a)

In [3]:
# array addition using numpy arithematic operation
a = np.array([1,2,3,4,5])
b = np.array([1,2,3,4,5]) 
numpyadd = np.add(a,b) # We can also write numpyadd = a+b
print(numpyadd)

[ 2  4  6  8 10]


In [4]:
# array subtraction using numpy arithematic operation
a = np.array([1,2,3,4,5])
b = np.array([1,2,3,4,5]) 
numpysub = np.subtract(a,b)
print(numpysub)

[0 0 0 0 0]


In [5]:
# array multiplication using numpy arithematic operation
a = np.array([1,2,3,4,5])
b = np.array([1,2,3,4,5]) 
numpymul = np.multiply(a,b)
print(numpymul)

[ 1  4  9 16 25]


In [6]:
# array division using numpy arithematic operation
a = np.array([1,2,3,4,5])
b = np.array([1,2,3,4,5]) 
numpydiv = np.divide(a,b)
print(numpydiv)

[1. 1. 1. 1. 1.]


In [10]:
# array mod using numpy arithematic operation
a = np.array([1,2,3,4,5])
b = np.array([1,2,3,4,5]) 
numpymod = np.mod(a,b)
print(numpymod)

[0 0 0 0 0]


In [7]:
# array power using numpy arithematic operation
a = np.array([1,2,3,4,5])
b = np.array([1,2,3,4,5]) 
numpypow = np.power(a,b)
print(numpypow)

[   1    4   27  256 3125]


In [13]:
# array reciprocal using numpy arithematic operation
a = np.array([1,2,3,4,5])
b = np.array([1,2,3,4,5]) 
numpyrec = np.reciprocal(a,b)
print(numpyrec)

[1 0 0 0 0]


## NumPy Aggregation Operations

In [12]:
# np.min(x)
# np.max(x)
# np.argmin(x)
# np.argmax(x)
# np.mean(x)
# np.median(x)
# np.sqrt(x)
# np.sin(x)
# np.cos(x)
# np.cumsum(x)

In [13]:
# code to find the minimum element from the numpy array and its position in the array 
var = np.array([1,2,3,4,5])
print(f"Minimum element : {np.min(var)}")
print(f"Index of minimum element : {np.argmin(var)}")

Minimum element : 1
Index of minimum element : 0


In [14]:
# code to find the maximum element from the numpy array and its position in the array 
var = np.array([1,2,3,4,5])
print(f"Maximum element : {np.max(var)}")
print(f"Index of maximum element : {np.argmax(var)}")

Maximum element : 5
Index of maximum element : 4


In [18]:
# code to find the mean of the array elements
var = np.array([1,2,3,4,5])
print(f"Mean : {np.mean(var)}")

Mean : 3.0


In [19]:
# code to find the median of the array elements
var = np.array([1,2,3,4,5])
print(f"Median : {np.median(var)}")

Median : 3.0


In [15]:
var = np.array([1,2,3,4,5])
print(f"Square root : {np.sqrt(var)}")

Square root : [1.         1.41421356 1.73205081 2.         2.23606798]


In [16]:
var = np.array([1,2,3,4,5])
print(f"Sin value : {np.sin(var)}")

Sin value : [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [17]:
var = np.array([1,2,3,4,5])
print(f"Cos value : {np.cos(var)}")

Cos value : [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]


## Shape and Reshaping in NumPy Arrays

In [8]:
var = np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(var)
print()
print(f"Shape of the array is : {var.shape}") # Returns the number of rows and columns of an array

[[1 2 3 4 5]
 [1 2 3 4 5]]

Shape of the array is : (2, 5)


In [8]:
# how to create a multidimentional array
var = np.array([1,2,3,4,5], ndmin = 5)
print(f"This is a {var.ndim}D array")
print(var)
print()
print(f"Shape of the array is : {var.shape}")

This is a 5D array
[[[[[1 2 3 4 5]]]]]

Shape of the array is : (1, 1, 1, 1, 5)


In [28]:
# how to convert a 1d array to a 2d array
var = np.array([1,2,3,4,5,6])
print(f"This is a {var.ndim}D array")
print(var)
print()

x = var.reshape(3,2)
print(f"This is a {x.ndim}D array")
print(x)
print()

y = var.reshape(2,3)
print(f"This is a {y.ndim}D array")
print(y)

This is a 1D array
[1 2 3 4 5 6]

This is a 2D array
[[1 2]
 [3 4]
 [5 6]]

This is a 2D array
[[1 2 3]
 [4 5 6]]


In [13]:
# how to convert a 1d array to a 3d array
var = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(f"This is a {var.ndim}D array")
print(var)
print()

x = var.reshape(2,3,2)
print(f"This is a {x.ndim}D array")
print(x)

This is a 1D array
[ 1  2  3  4  5  6  7  8  9 10 11 12]

This is a 3D array
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [14]:
# how to convert a 2d array to a 1d array (Reverse process)
var = np.array([1,2,3,4,5,6])
print(f"This is a {var.ndim}D array")
print(var)
print()

x = var.reshape(2,3)
print(f"This is a {x.ndim}D array")
print(x)
print()

y = x.reshape(-1)
print(f"This is a {y.ndim}D array")
print(y)

This is a 1D array
[1 2 3 4 5 6]

This is a 2D array
[[1 2 3]
 [4 5 6]]

This is a 1D array
[1 2 3 4 5 6]


In [15]:
# how to convert a 3d array to a 1d array (Reverse process)
var = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(f"This is a {var.ndim}D array")
print(var)
print()

x = var.reshape(2,3,2)
print(f"This is a {x.ndim}D array")
print(x)
print()

y = x.reshape(-1)
print(f"This is a {y.ndim}D array")
print(y)

This is a 1D array
[ 1  2  3  4  5  6  7  8  9 10 11 12]

This is a 3D array
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]

This is a 1D array
[ 1  2  3  4  5  6  7  8  9 10 11 12]


## Broadcasting In Numpy Arrays

In [26]:
x = np.array([1,2,3,4,5])
y = np.array([1,2,3,4])

print(x+y)

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

In [27]:
x = np.array([1,2,3,4,5])
y = np.array([1,2,3,4,5])

print(x+y)

[ 2  4  6  8 10]


In [20]:
x = np.array([1,2,3,4,5])
print(f"Shape of the array is : {x.shape}")
print(x)
print()

y = np.array([[1],[2],[3],[4],[5]])
print(f"Shape of the array is : {y.shape}")
print(y)
print()

z = x+y
print(f"Shape of the array is : {z.shape}")
print(z)

Shape of the array is : (5,)
[1 2 3 4 5]

Shape of the array is : (5, 1)
[[1]
 [2]
 [3]
 [4]
 [5]]

Shape of the array is : (5, 5)
[[ 2  3  4  5  6]
 [ 3  4  5  6  7]
 [ 4  5  6  7  8]
 [ 5  6  7  8  9]
 [ 6  7  8  9 10]]


In [21]:
x = np.array([1,2,3,4,5])
print(f"Shape of the array is : {x.shape}")
print(x)
print()

y = np.array([[1],[2],[3],[4],[5]])
print(f"Shape of the array is : {y.shape}")
print(y)
print()

z = np.add(x,y)
print(f"Shape of the array is : {z.shape}")
print(z)

Shape of the array is : (5,)
[1 2 3 4 5]

Shape of the array is : (5, 1)
[[1]
 [2]
 [3]
 [4]
 [5]]

Shape of the array is : (5, 5)
[[ 2  3  4  5  6]
 [ 3  4  5  6  7]
 [ 4  5  6  7  8]
 [ 5  6  7  8  9]
 [ 6  7  8  9 10]]


## Indexing In NumPy Arrays

In [16]:
# 1d Array
# Indexing      
# Array =             [ 9 , 8 , 7 , 6 , 5 ]
# Positive Indexing =   0 , 1 , 2 , 3 , 4
# Negative Indexing =  -5, -4, -3, -2, -1

var = np.array([9,8,7,6,5])
print(var[3])
print(var[-2])

6
6


In [21]:
# 2d Array
var = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(f"This is a {var.ndim}D array")
print(var)
print()
print(var[0,4]) # We can use this notation for indexing in a 2d array
print(var[1][4]) # we can also use this notation for indexing in a 2d array

This is a 2D array
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

5
10


In [37]:
# 3d Array
# var = np.array([1,2,3,4,5], ndmin = 3)
var = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(f"This is a {var.ndim}D array")
print(var)
print()
print(var[0,0,1])
print(var[0,1,1])
print(var[1,0,1])
print(var[1,1,1])

This is a 3D array
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

2
4
6
8


## Slicing In NumPy Arrays

In [52]:
var = np.array([1,2,3,4,5])
print(var)
print(var[1:3])
print(var[1:])
print(var[:3]) 
print(var[::2]) # print array by skipping 1 value or step
print(var[0:5:2]) # print array by skipping 1 value
print(var[::-1]) # print array reverse

[1 2 3 4 5]
[2 3]
[2 3 4 5]
[1 2 3]
[1 3 5]
[1 3 5]
[5 4 3 2 1]


In [67]:
# Slicing in 2d array
var = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(f"This is a {var.ndim}D array")
print(var)
print()
print(var[0,1:4])
print()
print(var[1,1:4])
print()
print(var[2,1:4])

This is a 2D array
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

[2 3 4]

[7 8 9]

[12 13 14]


## Iterating NumPy Arrays

In [81]:
# Iteration of 1d array
var = np.array([11,12,13,14,15])
print("Printing values horizontally")
for i in var:
    print(i,end=" ")
    
print()
print("Printing values vertically")
for i in range(0,5):
    print(var[i])

Printing values horizontally
11 12 13 14 15 
Printing values vertically
11
12
13
14
15


In [91]:
# Iteration of 2d array
var = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(var)
print()

for i in var:
    for j in i:
        print(j, end = " ")
    print()

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

1 2 3 4 5 
6 7 8 9 10 


In [96]:
# Iteration of 3d array
# var = np.array([[[1,2,3,4,5],[6,7,8,9,10]]])
var = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(var)
print()

for i in var:
    for j in i:
        for k in j:
            print(k, end = " ")
        print()

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

1 2 
3 4 
5 6 
7 8 


In [101]:
# Using numpy's inbuilt function (nditer) for iteration 
var = np.array([[[1,2,3,4,5],[6,7,8,9,10]]])
for i in np.nditer(var):
    print(i)

1
2
3
4
5
6
7
8
9
10


In [103]:
# Printing values with index using numpy's inbuilt function
var = np.array([[[1,2,3,4,5],[6,7,8,9,10]]])
for i,d in np.ndenumerate(var):
    print(i,d)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 0, 4) 5
(0, 1, 0) 6
(0, 1, 1) 7
(0, 1, 2) 8
(0, 1, 3) 9
(0, 1, 4) 10
